In [1]:
%matplotlib inline

import numpy as np
import sympy as sp
import random 
import matplotlib.pyplot as plt

In [2]:
n = int(input("input n:"))
p = int(input("input p:"))

input n:15
input p:3


In [3]:
M = np.identity(n, sp.Rational)

In [4]:
def operation1(M):
    row = random.randint(0, n-1)
    M[row] *= random.randint(2, 100)
    return row
def operation2(M):
    rand_row2 = rand_row1 = random.randint(0, n-1)
    while rand_row2 == rand_row1:
        rand_row2 = random.randint(0, n-1)
    M[[rand_row1, rand_row2], :] = M[[rand_row2, rand_row1], :]
def operation3(M):
    rand_row2 = rand_row1 = random.randint(0, n-1)
    while rand_row2 == rand_row1:
        rand_row2 = random.randint(0, n-1)
    M[rand_row2] += M[rand_row1] * random.randint(1, 100)
    return rand_row1, rand_row2

In [5]:
if p == 1:
    operation1(M)
elif p == 2:
    operation2(M)
elif p == 3:
    operation3(M)
print(" Elementary matrix using operation", p, ":\n", M)

 Elementary matrix using operation 3 :
 [[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 73 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [6]:
def inv(op, rand_row1, rand_row2):
    if op == 1:
        A[rand_row1][rand_row1] = sp.Rational(1, A[rand_row1][rand_row1])
    elif op == 3:
        A[rand_row2][rand_row1] *= -1

In [7]:
M = M_inv = np.identity(n, sp.Rational)
rand_row2 = 0

for i in range(50):
    A = np.identity(n, sp.Rational)
    rand = random.randint(1, 3)
    if rand == 1:
        rand_row1 = operation1(A)
    elif rand == 2:
        operation2(A)
    elif rand == 3:
        rand_row1, rand_row2 = operation3(A)
    M = A.dot(M)
    inv(rand, rand_row1, rand_row2)
    M_inv = M_inv.dot(A)

print("Invertible matrix M:\n", M)
print("\nM's inverse:\n", M_inv)
print("\nM dot M's inverse:\n", M.dot(M_inv))

Invertible matrix M:
 [[0 0 0 0 7 0 0 0 0 0 0 35 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 77700 0 0 0 0 0 0 0 819 0 0 0 0 0]
 [0 0 100 244400 0 0 0 1 0 0 25568000 0 0 0 0]
 [0 806137500 2905 7099820 1061321 1577 0 0 0 0 742750400 4967550 415 0 0]
 [0 0 0 0 0 0 0 0 0 0 2295 0 0 0 0]
 [0 0 1 2444 0 0 0 0 0 0 255680 0 0 0 0]
 [0 0 93 227292 0 0 0 0 0 0 23778240 9603 0 0 6208]
 [0 0 0 0 0 0 0 0 1456 2704 0 0 0 0 0]
 [0 0 0 0 203 0 5 0 0 0 0 1015 0 0 0]
 [0 0 0 26 0 0 0 0 0 0 2720 0 0 7 0]
 [0 0 0 0 673 1 0 0 0 0 0 3150 0 0 0]
 [0 0 0 0 9135 0 225 0 0 0 0 45675 0 1 0]
 [1 0 0 0 2322 54 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 13 0 0 0 0 0]]

M's inverse:
 [[4860 0 0 0 0 0 0 0 0 0 0 -54 0 1 0]
 [0 0 1/77700 0 0 0 0 0 0 0 0 0 0 0 -3/3700]
 [0 0 0 0 0 0 1 0 0 -29610 -94 0 658 0 0]
 [0 0 0 0 0 -16/351 0 0 0 315/26 1/26 0 -7/26 0 0]
 [1/7 -5 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [-673/7 215 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [-29/5 0 0 0 0 0 0 0 0 1/5 0 0 0 0 0]
 [0 0 0 1 0 0 -100 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0